UPDATE `email_template` SET `title` = 'Vendors Account Opening' WHERE `email_template`.`email_template_id` = 4;

INSERT INTO `email_template` (`email_template_id`, `title`, `subject`, `body`) VALUES (NULL, 'Users Account Opening', 'Account Opening', '<p><span [removed]="font-weight: bold;">Hi [[to]],</span></p><p><span [removed]="font-weight: bold;">Thank you for registering at our site&nbsp;</span>[[sitename]]<span [removed]="font-weight: bold;">.</span></p><p><span [removed]="font-weight: bold;">Your account type is : [[account_type]]</span></p><p><span [removed]="font-weight: bold;">Email is : [[email]]</span></p><p><span [removed]="font-weight: bold;"></span></p><p><span [removed]="font-weight: bold;">Password is : [[password]]</span></p><p>Login from here : [[url]]</p><p><span [removed]="font-weight: bold;">Please contact with the&nbsp;</span>administration&nbsp;team if you have any further question. Best wishes.<br></p><p><span [removed]="font-weight: bold;"><br></span></p><p><span [removed]="font-weight: bold;">Thanks,</span></p><p><span [removed]="" bold;"="">[[from]]</span></p>'), (NULL, 'Admins Account Opening', 'Account Opening', '<p><span [removed]="font-weight: bold;">Hi [[to]],</span></p><p><span [removed]="font-weight: bold;">Thank you for joining at our site&nbsp;</span>[[sitename]]<span [removed]="font-weight: bold;">.</span></p><p><span [removed]="font-weight: bold;">Your account type is : [[account_type]]</span></p><p><span [removed]="font-weight: bold;">Email is : [[email]]</span></p><p><span [removed]="font-weight: bold;"></span></p><p><span [removed]="font-weight: bold;">Password is : [[password]]</span></p><p>Login from here : [[url]]</p><p>&nbsp;Best wishes.</p><p><br></p><p><span [removed]="font-weight: bold;">Thanks,</span></p><p><span [removed]="" bold;"="">[[from]]</span></p>');

INSERT INTO `ui_settings` (`ui_settings_id`, `type`, `value`) VALUES (NULL, 'email_theme_style', 'style_1'), (NULL, 'email_theme_style_2', '<div style="margin: 0px 10px; background: #45a9b9; padding: 30px;"><div style="margin: 0px auto; background: #eff7ff; padding: 30px;">[[body]]</div></div>'), (NULL, 'email_theme_style_3', '<div style="margin: 0px 10px; background: repeating-linear-gradient(-45deg, red 0, red 1em, #fffdeb 0, #fffdeb 2em, #58a 0, #58a 3em, #fffdeb 0, #fffdeb 4em); padding: 15px;"><div style="margin: 0px auto; background: #fffdeb; padding: 30px;">[[body]]</div></div>'), (NULL, 'email_theme_style_4', '<div style="margin: 0px 10px; background: #f7f7f7; padding: 30px;"><div style="padding: 30px; background: #76cece; border-radius:5px 5px 0px 0px; box-shadow: 0px -1px 7px #616565; display:block;"><div style="background-image:url([[logo]]); background-repeat:no-repeat; height:80px; width:auto; display:block;"></div></div><div style="margin: 0px auto; background: rgba(255, 255, 255, 0.91); padding: 30px; box-shadow: 0px 3px 7px #616565; border-radius:0px 0px 5x 5px;">[[body]]</div></div>');

INSERT INTO `business_settings` (`business_settings_id`, `type`, `status`, `value`) VALUES (NULL, 'currency_format', NULL, 'us'), (NULL, 'symbol_format', NULL, 's_amount'), (NULL, 'no_of_decimals', NULL, '2');

INSERT INTO `business_settings` (`business_settings_id`, `type`, `status`, `value`) VALUES (NULL, 'vp_set', NULL, NULL), (NULL, 'vp_merchant_id', NULL, NULL);

ALTER TABLE  `vendor` ADD  `vp_set` VARCHAR( 50 ) NULL ,
ADD  `vp_merchant_id` VARCHAR( 500 ) NULL ;